In [3]:
import os

In [4]:
print(len(os.listdir('positive')))
print(len(os.listdir('negative')))
print(len(os.listdir('anchor')))

294
13233
191


In [5]:
input_img = os.listdir('positive')[:250]
input_img = ['./positive/'+x for x in input_img]
val_image = os.listdir('negative')[:125]
val_image = ['./negative/'+x for x in val_image]
val_image.extend(os.listdir('anchor')[:125])
val_image[125:] = ['./anchor/'+x for x in val_image[125:]]

In [6]:
input_img

['./positive/c0ba1c70-f3cc-11ee-8c4c-973b43a59e11.jpg',
 './positive/c10d6f47-f3cc-11ee-968c-973b43a59e11.jpg',
 './positive/c11b8984-f3cc-11ee-9165-973b43a59e11.jpg',
 './positive/c129d2e5-f3cc-11ee-9c8b-973b43a59e11.jpg',
 './positive/c137fdce-f3cc-11ee-b382-973b43a59e11.jpg',
 './positive/c14d3620-f3cc-11ee-886a-973b43a59e11.jpg',
 './positive/c15b3c88-f3cc-11ee-b230-973b43a59e11.jpg',
 './positive/c169890c-f3cc-11ee-9803-973b43a59e11.jpg',
 './positive/c1709681-f3cc-11ee-95ff-973b43a59e11.jpg',
 './positive/c17f1d66-f3cc-11ee-b079-973b43a59e11.jpg',
 './positive/c192075d-f3cc-11ee-84c5-973b43a59e11.jpg',
 './positive/c1b9fb49-f3cc-11ee-b2b7-973b43a59e11.jpg',
 './positive/c1c8353d-f3cc-11ee-95d9-973b43a59e11.jpg',
 './positive/c1d69bb8-f3cc-11ee-ad5c-973b43a59e11.jpg',
 './positive/c1e4f071-f3cc-11ee-b9e0-973b43a59e11.jpg',
 './positive/c1f31701-f3cc-11ee-8c0b-973b43a59e11.jpg',
 './positive/c2017d53-f3cc-11ee-a7de-973b43a59e11.jpg',
 './positive/c20ff0d2-f3cc-11ee-aa15-973b43a59e1

In [7]:
val_image

['./negative/Aaron_Eckhart_0001.jpg',
 './negative/Aaron_Guiel_0001.jpg',
 './negative/Aaron_Patterson_0001.jpg',
 './negative/Aaron_Peirsol_0001.jpg',
 './negative/Aaron_Peirsol_0002.jpg',
 './negative/Aaron_Peirsol_0003.jpg',
 './negative/Aaron_Peirsol_0004.jpg',
 './negative/Aaron_Pena_0001.jpg',
 './negative/Aaron_Sorkin_0001.jpg',
 './negative/Aaron_Sorkin_0002.jpg',
 './negative/Aaron_Tippin_0001.jpg',
 './negative/Abbas_Kiarostami_0001.jpg',
 './negative/Abba_Eban_0001.jpg',
 './negative/Abdel_Aziz_Al-Hakim_0001.jpg',
 './negative/Abdel_Madi_Shabneh_0001.jpg',
 './negative/Abdel_Nasser_Assidi_0001.jpg',
 './negative/Abdel_Nasser_Assidi_0002.jpg',
 './negative/Abdoulaye_Wade_0001.jpg',
 './negative/Abdoulaye_Wade_0002.jpg',
 './negative/Abdoulaye_Wade_0003.jpg',
 './negative/Abdoulaye_Wade_0004.jpg',
 './negative/Abdulaziz_Kamilov_0001.jpg',
 './negative/Abdullah_0001.jpg',
 './negative/Abdullah_0002.jpg',
 './negative/Abdullah_0003.jpg',
 './negative/Abdullah_0004.jpg',
 './nega

In [8]:
import numpy as np

pred = [0]*125 +[1]*125

In [9]:
import pandas as pd
data = {'input_image':input_img, "validation_image":val_image, "target":pred}
dataset = pd.DataFrame(data= data)

In [10]:
dataset

input_image  \
0    ./positive/c0ba1c70-f3cc-11ee-8c4c-973b43a59e1...   
1    ./positive/c10d6f47-f3cc-11ee-968c-973b43a59e1...   
2    ./positive/c11b8984-f3cc-11ee-9165-973b43a59e1...   
3    ./positive/c129d2e5-f3cc-11ee-9c8b-973b43a59e1...   
4    ./positive/c137fdce-f3cc-11ee-b382-973b43a59e1...   
..                                                 ...   
245  ./positive/ceaf8605-f3cc-11ee-91a5-973b43a59e1...   
246  ./positive/cebde388-f3cc-11ee-b447-973b43a59e1...   
247  ./positive/cecc0c1a-f3cc-11ee-9dc1-973b43a59e1...   
248  ./positive/cee168ba-f3cc-11ee-9e04-973b43a59e1...   
249  ./positive/cef68262-f3cc-11ee-aa40-973b43a59e1...   

                                      validation_image  target  
0                    ./negative/Aaron_Eckhart_0001.jpg       0  
1                      ./negative/Aaron_Guiel_0001.jpg       0  
2                  ./negative/Aaron_Patterson_0001.jpg       0  
3                    ./negative/Aaron_Peirsol_0001.jpg       0  
4                    ./negative/Aaron_Peirsol_0002.jpg       0  
..                                                 ...     ...  
245  ./anchor/bb7725c1-f3cc-11ee-a6a3-973b43a59e11.jpg       1  
246  ./anchor/bb85281d-f3cc-11ee-9a18-973b43a59e11.jpg       1  
247  ./anchor/bb936026-f3cc-11ee-a834-973b43a59e11.jpg       1  
248  ./anchor/bba198b5-f3cc-11ee-9363-973b43a59e11.jpg       1  
249  ./anchor/bbaffb74-f3cc-11ee-a4a7-973b43a59e11.jpg       1  

[250 rows x 3 columns]

In [11]:
from sklearn.metrics import classification_report

In [12]:
import keras
import tensorflow as tf
class L1Dist(keras.layers.Layer):
    def __init__(self, **kwargs):
        super(L1Dist, self).__init__(**kwargs)

    def call(self, input_embedding, validation_embedding):
        return tf.math.abs(input_embedding[0] - validation_embedding[0])


In [13]:
from keras.models import load_model
models = {
    'siamese':load_model('siamesemodel.keras', custom_objects={'L1Dist':L1Dist}),
    'vgg': load_model('vgg_model.keras', custom_objects={'L1Dist':L1Dist}),
    'mbnv2': load_model('mbnv2_model.keras', custom_objects={'L1Dist':L1Dist}),
}

In [14]:


def preprocess(file_path):
    # Read in image from file path 
    byte_img = tf.io.read_file(file_path)
    
    # Load in the image 
    img = tf.io.decode_jpeg(byte_img)
    
    # Preprocessing steps - resizing the image to be 100x100x3
    img = tf.image.resize(img, (100,100))
    # Scale image to be between 0 and 1 
    img = img / 255.0
    img = tf.reshape(img,[-1,100,100,3])
    # Return image
    return img

In [15]:
x1 = dataset['input_image']
x2 = dataset['validation_image']

In [16]:
x1 = x1.apply(preprocess)
x2 = x2.apply(preprocess)


In [17]:
x1

0      (((tf.Tensor([0.7490196 0.6901961 0.6156863], ...
1      (((tf.Tensor([0.7921569  0.72156864 0.6431373 ...
2      (((tf.Tensor([0.79093134 0.7203431  0.64191175...
3      (((tf.Tensor([0.785049   0.71838236 0.6477941 ...
4      (((tf.Tensor([0.79093134 0.7203431  0.6340686 ...
                             ...                        
245    (((tf.Tensor([0.7894608  0.71887255 0.6404412 ...
246    (((tf.Tensor([0.77181375 0.7012255  0.6071078 ...
247    (((tf.Tensor([0.8036765  0.72132355 0.6389706 ...
248    (((tf.Tensor([0.7740196  0.70735294 0.64460784...
249    (((tf.Tensor([0.79240197 0.7257353  0.64730394...
Name: input_image, Length: 250, dtype: object

In [18]:
x2

0      (((tf.Tensor([0. 0. 0.], shape=(3,), dtype=flo...
1      (((tf.Tensor([0. 0. 0.], shape=(3,), dtype=flo...
2      (((tf.Tensor([0. 0. 0.], shape=(3,), dtype=flo...
3      (((tf.Tensor([0.9166667 0.9519608 0.9401961], ...
4      (((tf.Tensor([0.9382353  0.94803923 0.85294116...
                             ...                        
245    (((tf.Tensor([0.8004902  0.7465686  0.68088233...
246    (((tf.Tensor([0.7561275 0.7269608 0.652451 ], ...
247    (((tf.Tensor([0.23921569 0.23529412 0.22745098...
248    (((tf.Tensor([0.19338235 0.18946078 0.18161765...
249    (((tf.Tensor([0.21740197 0.2134804  0.19779412...
Name: validation_image, Length: 250, dtype: object

In [19]:
list(zip(x1,x2))[0]

(<tf.Tensor: shape=(1, 100, 100, 3), dtype=float32, numpy=
 array([[[[0.7490196 , 0.6901961 , 0.6156863 ],
          [0.75490195, 0.69509804, 0.62352943],
          [0.75490195, 0.69215685, 0.62941176],
          ...,
          [0.92058825, 0.87352943, 0.8264706 ],
          [0.92058825, 0.87058824, 0.83235294],
          [0.90882355, 0.86960787, 0.8303922 ]],
 
         [[0.7647059 , 0.69803923, 0.627451  ],
          [0.76862746, 0.70759803, 0.6360294 ],
          [0.76666665, 0.70490193, 0.6392157 ],
          ...,
          [0.93284315, 0.87941176, 0.83406866],
          [0.935049  , 0.8838235 , 0.84436274],
          [0.93602943, 0.8840686 , 0.8487745 ]],
 
         [[0.78210783, 0.71544117, 0.6389706 ],
          [0.7830882 , 0.7169118 , 0.6460784 ],
          [0.7867647 , 0.7264706 , 0.6526961 ],
          ...,
          [0.9411765 , 0.8862745 , 0.8372549 ],
          [0.94779414, 0.8928922 , 0.8497549 ],
          [0.95      , 0.89509803, 0.8539216 ]],
 
         ...,
 
       

In [22]:
y_pred = [models['siamese'].predict([input_image, validation_image])[0][0] for input_image, validation_image in list(zip(x1,x2))]
y_pred = [0 if i<0.5 else 1 for i in y_pred]
print(classification_report(dataset['target'], y_pred))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 66ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 57ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 58ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 56ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step
1/1 ━━━━━━━━

In [25]:
y_pred = [models['vgg'].predict([input_image, validation_image])[0][0] for input_image, validation_image in list(zip(x1,x2))]
y_pred = [0 if i<0.5 else 1 for i in y_pred]
print(classification_report(dataset['target'], y_pred))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 72ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 80ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 93ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 81ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 84ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 74ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 64ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 68ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 65ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 62ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 63ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 61ms/step
1/1 ━━━━━━━━

In [26]:
y_pred = [models['mbnv2'].predict([input_image, validation_image])[0][0] for input_image, validation_image in list(zip(x1,x2))]
y_pred = [0 if i<0.5 else 1 for i in y_pred]
print(classification_report(dataset['target'], y_pred))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 29ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 33ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 35ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 31ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 32ms/step
1/1 ━━━━━━━━

In [27]:
dataset.to_csv('eval.csv')